### PR TITLE
QA -  Prevent error “No such property: container for class: org.apache.c...

### PR DESCRIPTION
**Pull request by moskinson**
Hi,
This plugin is very useful for us to prevent session`s lost in production. I have changed some things to have the log more clean in development

I was having repetitive error in log with the plugin, the Manager was not used anywhere and causing this log error. I have deleted it. Also, I have change the future deprecated ConfigurationHolder

Let me know if you are agree or not with the changes

Thanks,

Best Regards

-05-09 11:43:13,706 [http-bio-8443-exec-2] ERROR session.SessionTrackerValve  - An unexpected error occured while attempting to deserialize the session : No such property: container for class: org.apache.catalina.connector.Connector
Message: No such property: container for class: org.apache.catalina.connector.Connector
    Line | Method
->>  132 | deSerialize  in com.dawsonsystems.session.SessionTrackerValve

---

|     79 | storeSession in     ''
|     29 | invoke . . . in     ''
|   1145 | runWorker    in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    744 | run          in java.lang.Thread

### CODE REVIEW

**Comment by moskinson** [comment]
Please, Could you check this commit?

**Comment by moskinson** [comment]
Great! Thank you

**Comment by daviddawson** [comment]
No probs, sorry, I missed this come in.

**Comment by daviddawson** [comment]
This has been published as version 0.6, which should appear on the portal soon.

Thanks!

**Comment by moskinson** [comment]
Perfect! It is very useful for us right now

All the best

**Pull request merged**
